services:
  db:
    container_name: db
    hostname: db
    image: postgres:17.0-alpine3.20
    restart: unless-stopped
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_HOST: "127.0.0.1"
      POSTGRES_PORT: 5432
      POSTGRES_DB: "db"
    networks:
      - proxy-net
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db:

networks:
  proxy-net:
    name: proxy-net
    driver: bridge
