definitions:
  dto.CreateUserRequest:
    properties:
      confirm_password:
        example: scrubs
        type: string
      email:
        example: j.dorian@example.com
        type: string
      full_name:
        example: John Dorian
        type: string
      password:
        example: scrubs
        type: string
      username:
        example: JD
        type: string
    required:
    - confirm_password
    - email
    - full_name
    - password
    - username
    type: object
  dto.LoginRequest:
    properties:
      password:
        example: password
        type: string
      username:
        example: John Doe
        type: string
    required:
    - password
    - username
    type: object
  dto.LoginResponse:
    properties:
      access_token:
        example: access_token
        type: string
    type: object
  dto.UpdateUserRequest:
    properties:
      custom_fields:
        additionalProperties:
          type: string
        example:
          key: value
        type: object
      email:
        example: j.dorian@example.com
        type: string
      full_name:
        example: John Dorian
        type: string
      user_id:
        example: 3a282222-2100-4ff7-9849-71b853da0926
        type: string
      username:
        example: JD
        type: string
    type: object
  dto.UserBriefResponse:
    properties:
      user_id:
        example: 3a282222-2100-4ff7-9849-71b853da0926
        type: string
    type: object
  dto.UserResponse:
    properties:
      active:
        example: true
        type: boolean
      created_at:
        example: "2020-12-31T23:59:59Z"
        type: string
      custom_fields:
        additionalProperties:
          type: string
        example:
          key: value
        type: object
      email:
        example: j.dorian@example.com
        type: string
      full_name:
        example: John Dorian
        type: string
      hidden:
        example: false
        type: boolean
      last_login:
        example: "2020-12-31T23:59:59Z"
        type: string
      updated_at:
        example: "2020-12-31T23:59:59Z"
        type: string
      user_id:
        example: 3a282222-2100-4ff7-9849-71b853da0926
        type: string
      username:
        example: JD
        type: string
    type: object
  lib.HTTPError:
    properties:
      msg:
        type: string
      result:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/auth/login:
    post:
      description: User login to the system
      parameters:
      - description: Login
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/lib.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/lib.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/lib.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/lib.HTTPError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/lib.HTTPError'
      summary: User login to the system
      tags:
      - Auth
  /v1/user:
    post:
      description: Creating a new user
      parameters:
      - description: User
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserBriefResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/lib.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/lib.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/lib.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/lib.HTTPError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/lib.HTTPError'
      summary: Creating a new user
      tags:
      - User
  /v1/user/{user_id}:
    get:
      description: Get user by ID
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/lib.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/lib.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/lib.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/lib.HTTPError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/lib.HTTPError'
      summary: Get user by ID
      tags:
      - User
    put:
      description: Updating user data
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: User
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/lib.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/lib.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/lib.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/lib.HTTPError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/lib.HTTPError'
      summary: Updating user data
      tags:
      - User
swagger: "2.0"
