definitions:
  common.HTTPError:
    properties:
      msg:
        type: string
      result:
        type: string
    type: object
  schemes.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  schemes.LoginResponse:
    properties:
      access_token:
        type: string
    type: object
  schemes.RegisterUserRequest:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - confirm_password
    - email
    - password
    - username
    type: object
  schemes.RegisterUserResponse:
    properties:
      user_id:
        type: string
    type: object
  schemes.UserBriefResponse:
    properties:
      user_id:
        type: string
    type: object
  schemes.UserRequest:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - confirm_password
    - email
    - password
    - username
    type: object
  schemes.UserResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      is_active:
        type: boolean
      last_login_date:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/login:
    post:
      description: User login to the system
      parameters:
      - description: Login
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/schemes.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/common.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.HTTPError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/common.HTTPError'
      summary: User login to the system
      tags:
      - Auth
  /api/v1/auth/register:
    post:
      description: Registering a new user
      parameters:
      - description: User
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/schemes.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.RegisterUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/common.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.HTTPError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/common.HTTPError'
      summary: Registering a new user
      tags:
      - Auth
  /api/v1/user:
    post:
      description: Creating a new user
      parameters:
      - description: User
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/schemes.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/common.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.HTTPError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/common.HTTPError'
      summary: Creating a new user
      tags:
      - User
  /api/v1/user/{user_id}:
    delete:
      description: Delete user by ID
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.UserBriefResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/common.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.HTTPError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/common.HTTPError'
      summary: Delete user by ID
      tags:
      - User
    get:
      description: Get user by ID
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/common.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.HTTPError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/common.HTTPError'
      summary: Get user by ID
      tags:
      - User
    put:
      description: Updating user data
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: User
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/schemes.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemes.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/common.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/common.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.HTTPError'
        default:
          description: ""
          schema:
            $ref: '#/definitions/common.HTTPError'
      summary: Updating user data
      tags:
      - User
swagger: "2.0"
